name: Terraform build

on:
  workflow_dispatch:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ID_KEY }} # Your custom secret name for Access Key
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }} # Your custom secret name for Secret Key
          aws-region: eu-west-3 # Example EU region, replace with the specific one you're using

      - name: Check if DynamoDB Table Exists
        id: dynamodb_check
        run: |
          aws dynamodb describe-table --table-name terraform-state-lock --region eu-west-3 || echo "Table does not exist"
        continue-on-error: true

        # Create DynamoDB Table for Locking (if it doesn't already exist)
      - name: Create DynamoDB Table for Locking
        if: steps.dynamodb_check.outcome == 'failure' # Only run if DynamoDB doesn't exist
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./terraform/dynamodb

      - name: Check if Terraform Backend is initialized
        id: backend_check
        run: |
          if [ -f ".terraform/terraform.tfstate" ]; then
            echo "Terraform Backend already initialized"
          else
            echo "Terraform Backend not initialized"
            exit 1
          fi
        working-directory: ./terraform
        continue-on-error: true

      - name: Initialize Terraform
        if: steps.backend_check.outcome == 'failure'
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" >  ~/your_key.pem
          chmod 400  ~/your_key.pem

      - name: Check Generated Ansible Inventory
        run: cat ansible/inventory.yml

      - name: Extract HAProxy IP from inventory
        id: extract_haproxy_ip
        run: |
          HAPROXY_IP=$(grep -A 1 'haproxy' ansible/inventory.yml | awk '/ansible_host/ {print $2}')
          echo "HAPROXY_IP=$HAPROXY_IP" >> $GITHUB_ENV

      # Copy the SSH Key to the HAProxy instance using the extracted IP
      - name: Copy SSH Key to HAProxy
        run: |
          scp -o StrictHostKeyChecking=no -i  ~/your_key.pem  ~/your_key.pem ubuntu@${{ env.HAPROXY_IP }}:/home/ubuntu/your_key.pem
          ssh -i ~/your_key.pem ubuntu@${{ env.HAPROXY_IP }} "chmod 400  ~/your_key.pem"
      - name: Upload Inventory to S3
        run: aws s3 cp ansible/inventory.yml s3://terraform-state-restaurant-app/ansible/inventory.yml

      - name: Run Ansible Playbook to Install Docker
        run: |
          cd ansible
          ansible-playbook -i inventory.yml install_docker.yml
