name: Terraform CI/CD

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ID_KEY }} # Your custom secret name for Access Key
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }} # Your custom secret name for Secret Key
          aws-region: eu-west-3 # Example EU region, replace with the specific one you're using

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
